service: rippo-backend

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    name: Rippo-api
    authenticationType: API_KEY
    schema: graphql/schema.graphql

    mappingTemplates:
      - dataSource: ParentsTable
        type: Query
        field: getParent
      - dataSource: ChildsTable
        type: Query
        field: listChilds
      - dataSource: createChild
        type: Mutation
        field: createChild
      - dataSource: createParent
        type: Mutation
        field: createParent
      - dataSource: updateChildStatus
        type: Mutation
        field: updateChildStatus

    dataSources:
      - type: AMAZON_DYNAMODB
        name: ParentsTable
        description: Datasource for parents table
        config:
          tableName: parents
      - type: AMAZON_DYNAMODB
        name: ChildsTable
        description: Datasource for childs table
        config:
          tableName: childs
      - type: AMAZON_DYNAMODB
        name: DoctorsTable
        description: Datasource for doctors table
        config:
          tableName: doctors
      - type: AWS_LAMBDA
        name: createChild
        description: "Create Child DataSource"
        config:
          functionName: createChild
      - type: AWS_LAMBDA
        name: createParent
        description: "Create Parent DataSource"
        config:
          functionName: createParent
      - type: AWS_LAMBDA
        name: updateChildStatus
        description: "Update child status DataSource"
        config:
          functionName: updateChildStatus

functions:
  createChild:
    handler: handler.ChildHanlder
  createParent:
    handler: handler.ParentHanlder
  updateChildStatus:
    handler: handler.ChildHanlder

