service: rippo-backend

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    name: Rippo-api
    authenticationType: API_KEY
    schema: graphql/schema.graphql
    mappingTemplates:
      - dataSource: ParentsTable
        type: Query
        field: getParent
    dataSources:
      - type: AMAZON_DYNAMODB
        name: ParentsTable
        description: Datasource for parents table
        config:
          tableName: parents
      - type: AMAZON_DYNAMODB
        name: ChildsTable
        description: Datasource for childs table
        config:
          tableName: childs
      - type: AMAZON_DYNAMODB
        name: DoctorsTable
        description: Datasource for doctors table
        config:
          tableName: doctors

functions:
  hello:
    handler: handler.graphqlHandler
